name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore    
    - name: Install Muget
      uses: nuget/setup-nuget@v1
    - name: Add github repositories
      run: |
        nuget sources add https://nuget.pkg.github.com/zhaopan/index.json -name github -Username zhaopan -Password ${{secrets.HUB_NUGET_TOKEN}}
    - name: Publish Nuget
      run: |
        nuget push ./bin/Release/*.nupkg --source github -SkipDuplicate
## dotnet pack --configuration Release
